from authentik.lib.kerberos.exceptions import KerberosException


class KerberosProtocolException(KerberosException):
    pass
